# Generated by Django 5.0.5 on 2024-05-07 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=12)),
                ('time_zone', models.CharField(max_length=50)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.code')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.code')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('send_date', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.client')),
                ('mail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.mail')),
            ],
        ),
    ]
