# Generated by Django 5.0.5 on 2024-05-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_mail_end_date_alter_mail_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mail',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
